package it.polimi.se2018.model.events;

import it.polimi.se2018.network.visitor.MessageVisitorInterface;

public class PlayerMessageToolCard extends PlayerMessage implements Message {

    private int toolCard;

    /**
     * Message generated by the view and sent it to the Virtual View when the player wants to use a tool card
     * @param player player id using the tool card
     * @param toolCard tool card id chosen by the player
     */
    public PlayerMessageToolCard(int player, int toolCard){
        super(player);
        this.toolCard = toolCard;
    }

    public int getToolCard() {
        return toolCard;
    }

    @Override
    public void accept(MessageVisitorInterface messageVisitorInterface) {
        messageVisitorInterface.visitPlayerMessageToolCard(this);
    }
}
