package it.polimi.se2018.model.events;

import it.polimi.se2018.network.visitor.MessageVisitorInterface;

public class PlayerMessageNotAFK extends PlayerMessage {

    /**
     * Message generated by the view and sent it to the Virtual View when the player comes back from being afk
     * @param player player coming back into game
     */
    public PlayerMessageNotAFK(int player) {
        this.player = player;
    }

    @Override
    public void accept(MessageVisitorInterface messageVisitorInterface) {
        messageVisitorInterface.visitPlayerMessageNotAFK(this);
    }
}




